# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-21 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('include_file', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueueObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField()),
                ('description', models.CharField(max_length=64)),
                ('file', models.FileField(null=True, upload_to='')),
                ('start_timedate', models.DateTimeField(default=None)),
                ('reserved_time', models.IntegerField()),
                ('end_timedate', models.DateTimeField(default=None)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerqueue.Queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
