# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-22 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerqueue', '0002_auto_20171122_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={},
        ),
    ]
