# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerqueue', '0007_auto_20171122_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
