# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-20 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerqueue', '0008_queue_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueobject',
            name='submitted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
