# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-30 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printerqueue', '0010_auto_20171221_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueobject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queueobject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
